Panggat, Adrian C.
BSCS - 2B
March 13, 2024

In [15]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.preprocessing import StandardScaler

In [14]:
df = pd.read_csv ('/content/BankCustomerData.csv')
df.head()

age           job  marital  education default  balance housing loan  \
0   58    management  married   tertiary      no     2143     yes   no   
1   44    technician   single  secondary      no       29     yes   no   
2   33  entrepreneur  married  secondary      no        2     yes  yes   
3   47   blue-collar  married    unknown      no     1506     yes   no   
4   33       unknown   single    unknown      no        1      no   no   

   contact  day month  duration  campaign  pdays  previous poutcome  \
0  unknown    5   may       261         1     -1         0  unknown   
1  unknown    5   may       151         1     -1         0  unknown   
2  unknown    5   may        76         1     -1         0  unknown   
3  unknown    5   may        92         1     -1         0  unknown   
4  unknown    5   may       198         1     -1         0  unknown   

  term_deposit  
0           no  
1           no  
2           no  
3           no  
4           no

In [16]:
df_dummies = pd.get_dummies (df, drop_first = True)

In [17]:
from typing_extensions import assert_type
df_dummies ['balance'] = (df['age'] > 50).astype(int)

In [18]:
x = df_dummies.drop(['balance', 'age', 'duration', 'campaign', 'previous'], axis=1)
y = df_dummies ['age']

In [19]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3, random_state=42)

In [20]:
scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.fit_transform(x_test)

In [21]:
model = LogisticRegression()
model.fit(x_train_scaled,y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [22]:
y_pred = model.predict(x_test_scaled)

In [23]:
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report (y_test, y_pred)

print(f"Accuracy: {accuracy}")
print("Confusin Matrix")
print(conf_matrix)
print("Classification Report")
print(class_report)

Accuracy: 0.062226391494684175
Confusin Matrix
[[0 1 3 ... 0 0 0]
 [0 3 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
Classification Report
              precision    recall  f1-score   support

          18       0.00      0.00      0.00         5
          19       0.20      0.33      0.25         9
          20       0.00      0.00      0.00        14
          21       0.00      0.00      0.00        18
          22       0.06      0.10      0.07        21
          23       0.00      0.00      0.00        48
          24       0.09      0.02      0.04        85
          25       0.12      0.09      0.10       139
          26       0.10      0.10      0.10       215
          27       0.06      0.05      0.05       244
          28       0.06      0.03      0.04       290
          29       0.05      0.02      0.03       293
          30       0.10      0.21      0.14       476
          31       0.08      0.16      0.11       593


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.

Conclusion.

Strong predictive power was shown by the logistic regression model, which was especially impacted by characteristics including balance, length of last contact, and prior campaign encounters. This knowledge enables the bank to concentrate its marketing efforts on clients who exhibit these traits, possibly increasing the rate at which consumers subscribe to term deposits.